[colors.primary]
background = "#040916"
foreground = "#a7bfe0"

[colors.cursor]
text = "#040916"
cursor = "#a7bfe0"

[colors.vi_mode_cursor]
text = "#040916"
cursor = "#a7bfe0"

[colors.search.matches]
foreground = "#040916"
background = "#a7bfe0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#74859c"
background = "#a7bfe0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#040916"
red = "#4C316E"
green = "#3B437A"
yellow = "#304F97"
blue = "#3D4A97"
magenta = "#5A549A"
cyan = "#9A5EA5"
white = "#a7bfe0"

[colors.bright]
black = "#74859c"
red = "#4C316E"
green = "#3B437A"
yellow = "#304F97"
blue = "#3D4A97"
magenta = "#5A549A"
cyan = "#9A5EA5"
white = "#a7bfe0"

[colors.dim]
black = "#a7bfe0"
red = "#4C316E"
green = "#3B437A"
yellow = "#304F97"
blue = "#3D4A97"
magenta = "#5A549A"
cyan = "#9A5EA5"
white = "#74859c"
